FROM golang:1.23 AS build-stage

WORKDIR /app

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./ ./

WORKDIR /app/cmd/faccrual
RUN CGO_ENABLED=0 GOOS=linux go build 


FROM alpine:3.14

WORKDIR /app

COPY --from=build-stage /app/cmd/faccrual/faccrual ./

ENTRYPOINT ["/app/faccrual"]
